name: shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: pwd
        run: Get-Location
      - name: pwd on bash shell
        run: pwd
        shell: bash